namespace parsergenerator
{
    public enum Symbol 
    {
        NONE = 0,
        TIMES = 1,
        DIV = 2,
        MOD = 3,
        AND = 4,
        PLUS = 5,
        MINUS = 6,
        OR = 7,
        EQ = 8,
        NE = 9,
        LT = 10,
        GT = 11,
        LE = 12,
        GE = 13,
        PERIOD = 14,
        COMMA = 15,
        COLON = 16,
        RPAREN = 17,
        RBRAK = 18,
        OF = 19,
        THEN = 20,
        DO = 21,
        LPAREN = 22,
        LBRAK = 23,
        NOT = 24,
        BECOMES = 25,
        NUMBER = 26,
        IDENT = 27,
        SEMICOLON = 28,
        END = 29,
        ELSE = 30,
        IF = 31,
        WHILE = 32,
        ARRAY = 33,
        RECORD = 34,
        CONST = 35,
        TYPE = 36,
        VAR = 37,
        PROCEDURE = 38,
        BEGIN = 39,
        PROGRAM = 40,
        EOF = 41
    }
}